export const dummyPromotion: PromotionType[] = [
  {
    id: "id-1",
    title: "Title - 1",
    description: "Description - 1",
    type: "cashback",
    amount: 10,
    min_transaction: 0,
    expiry_date: new Date(),
    is_valid: true,
    userId: "",
    image_id: null,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "id-2",
    title: "Title - 2",
    description: "Description - 2",
    type: "cashback",
    amount: 10,
    min_transaction: 0,
    expiry_date: new Date(),
    is_valid: true,
    userId: "",
    image_id: null,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "id-2",
    title: "Title - 2",
    description: "Description - 2",
    type: "cashback",
    amount: 10,
    min_transaction: 0,
    expiry_date: new Date(),
    is_valid: true,
    userId: "",
    image_id: null,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "id-2",
    title: "Title - 2",
    description: "Description - 2",
    type: "cashback",
    amount: 10,
    min_transaction: 0,
    expiry_date: new Date(),
    is_valid: true,
    userId: "",
    image_id: null,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "id-2",
    title: "Title - 2",
    description: "Description - 2",
    type: "cashback",
    amount: 10,
    min_transaction: 0,
    expiry_date: new Date(),
    is_valid: true,
    userId: "",
    image_id: null,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "id-2",
    title: "Title - 2",
    description: "Description - 2",
    type: "cashback",
    amount: 10,
    min_transaction: 0,
    expiry_date: new Date(),
    is_valid: true,
    userId: "",
    image_id: null,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "id-2",
    title: "Title - 2",
    description: "Description - 2",
    type: "cashback",
    amount: 10,
    min_transaction: 0,
    expiry_date: new Date(),
    is_valid: true,
    userId: "",
    image_id: null,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "id-2",
    title: "Title - 2",
    description: "Description - 2",
    type: "cashback",
    amount: 10,
    min_transaction: 0,
    expiry_date: new Date(),
    is_valid: true,
    userId: "",
    image_id: null,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "id-2",
    title: "Title - 2",
    description: "Description - 2",
    type: "cashback",
    amount: 10,
    min_transaction: 0,
    expiry_date: new Date(),
    is_valid: true,
    userId: "",
    image_id: null,
    created_at: new Date(),
    updated_at: new Date(),
  },
];
